-- Schema simulating the production Odyssey-style court case management DB
-- (SQL Server) in Postgres, covering the tables needed by the reminder query.
--
-- Identifiers are deliberately UNQUOTED so Postgres folds them to lowercase
-- and queries written in prod (SQL Server) casing work unchanged.
-- Never quote identifiers in this schema or in the fixture files.

CREATE SCHEMA dbo;

-- Make unqualified names resolve to dbo for all future connections,
-- whatever POSTGRES_DB was named (\gexec runs the generated ALTER):
SELECT format('ALTER DATABASE %I SET search_path TO dbo, public', current_database())
\gexec

SET search_path TO dbo, public;

-- Generic code/description lookup, resolved in prod via dbo.fnGetLookupDescription
CREATE TABLE tblLookup (
    LookupType        text NOT NULL,
    LookupCode        text NOT NULL,
    LookupDescription text NOT NULL,
    PRIMARY KEY (LookupType, LookupCode)
);

-- Argument order matches the prod call site: dbo.fnGetLookupDescription(code, type)
CREATE FUNCTION fnGetLookupDescription(p_code text, p_type text)
RETURNS text
LANGUAGE sql STABLE
AS $$
    SELECT LookupDescription
    FROM dbo.tblLookup
    WHERE LookupCode = p_code AND LookupType = p_type;
$$;

CREATE TABLE tblParty (
    PartyID   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FirstName text NOT NULL,
    LastName  text NOT NULL
);

CREATE TABLE tblCase (
    CaseID           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CaseNumber       text NOT NULL UNIQUE,
    FirstDefendantID integer NOT NULL REFERENCES tblParty (PartyID),
    CaseType         text NOT NULL DEFAULT 'CRIMINAL',
    FiledDate        date
);

CREATE TABLE tblCaseParty (
    CasePartyID    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CaseID         integer NOT NULL REFERENCES tblCase (CaseID),
    PartyID        integer NOT NULL REFERENCES tblParty (PartyID),
    ConnectionType text NOT NULL DEFAULT 'DEFENDANT',
    UNIQUE (CaseID, PartyID)
);

-- No unique constraint on (PartyID, PhoneType, PhoneNumber): duplicate rows
-- exist in prod (data-entry dups) and the reminder query relies on DISTINCT
-- to collapse them, so fixtures seed one such duplicate on purpose.
CREATE TABLE tblPartyPhone (
    PartyPhoneID integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PartyID      integer NOT NULL REFERENCES tblParty (PartyID),
    PhoneType    text NOT NULL CHECK (PhoneType IN ('CELL', 'MOBILE', 'HOME', 'WORK', 'OTHER')),
    PhoneNumber  text NOT NULL
);

CREATE TABLE tblEventType (
    EventTypeID          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    EventTypeCode        text NOT NULL UNIQUE,
    EventTypeDescription text NOT NULL
);

-- A scheduled court session / calendar block; CourtRoomCode resolves through
-- tblLookup rows with LookupType = 'CourtRoom'
CREATE TABLE tblEvent (
    EventID       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CourtRoomCode text NOT NULL,
    JudgeName     text
);

-- Mirrors the prod quirk that the event type hangs off tblCaseEvent
-- (CaseEventTypeID), not tblEvent. CaseStartDateTime is timestamp WITHOUT
-- time zone to mirror SQL Server datetime; interpret as court-local time.
CREATE TABLE tblCaseEvent (
    CaseEventID       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CaseID            integer NOT NULL REFERENCES tblCase (CaseID),
    EventID           integer NOT NULL REFERENCES tblEvent (EventID),
    CaseEventTypeID   integer NOT NULL REFERENCES tblEventType (EventTypeID),
    CaseStartDateTime timestamp NOT NULL
);

CREATE INDEX idx_tblCaseEvent_start ON tblCaseEvent (CaseStartDateTime);
