"""Resolve database settings for the current environment.

Local development reads the COURT_DB_* variables that docker-compose.yml
also defaults (see .template.env). When deployed, COURT_DB_SECRET_ID names
(by ARN or name) the Secrets Manager secret generated by CourtDatabaseStack,
whose JSON (username, password, host, port, dbname) overrides the env values.
"""

import json
import os
from dataclasses import dataclass


@dataclass(frozen=True)
class DatabaseConfig:
    engine: str
    host: str
    port: int
    database: str
    user: str
    password: str

    @classmethod
    def from_env(cls, environ=None, secret_loader=None):
        environ = os.environ if environ is None else environ
        secret_loader = secret_loader or _load_secrets_manager_json

        secret = {}
        secret_name = environ.get("COURT_DB_SECRET_ID")
        if secret_name:
            secret = secret_loader(secret_name)

        return cls(
            engine=environ.get("COURT_DB_ENGINE", "postgres"),
            host=secret.get("host") or environ.get("COURT_DB_HOST", "localhost"),
            port=int(secret.get("port") or environ.get("COURT_DB_PORT", "5434")),
            database=secret.get("dbname") or environ.get("COURT_DB_NAME", "courtdb"),
            user=secret.get("username") or environ.get("COURT_DB_USER", "court"),
            password=secret.get("password")
            or environ.get("COURT_DB_PASSWORD", "court"),
        )


def _load_secrets_manager_json(secret_name):
    # Imported lazily: boto3 ships in the Lambda runtime but is not a
    # project dependency, and local development never reaches this path.
    import boto3

    client = boto3.client("secretsmanager")
    response = client.get_secret_value(SecretId=secret_name)
    return json.loads(response["SecretString"])
