#!/usr/bin/env bash
set -euo pipefail
. script/env


SEND_MESSAGE_FLAG=
if [[ -n ${1-} ]]; then SEND_MESSAGE_FLAG="--send $1"; fi;

uv run python script_helpers/truedialog_check.py $SEND_MESSAGE_FLAG 
