#!/bin/sh
. script/env

set -e

docker run --rm -it --network court-reminders_default postgres:16-alpine \
		psql "$(uv run --with boto3==1.40.3 python script_helpers/local_db_url.py --docker-network)"